version: '3.4'

services:
  php:
    image: 'badger/dev/php:7.4'
    environment:
      APP_ENV: '${APP_ENV:-prod}'
      COMPOSER_HOME: '/var/www/.composer'
      PHP_IDE_CONFIG: 'serverName=badger-cli'
      XDEBUG_ENABLED: '${XDEBUG_ENABLED:-0}'
      XDEBUG_CONFIG: 'remote_host=172.17.0.1'
    volumes:
      - './application:/srv/badger'
      - './features:/srv/features'
      - '${HOST_COMPOSER_HOME:-~/.composer}:/var/www/.composer'
    working_dir: '/srv/badger'
    command: 'php'
    networks:
      - 'badger'

  fpm:
    image: 'badger/dev/php:7.4'
    environment:
      APP_ENV: '${APP_ENV:-prod}'
      PHP_IDE_CONFIG: 'serverName=badger'
      XDEBUG_ENABLED: '${XDEBUG_ENABLED:-0}'
      XDEBUG_CONFIG: 'remote_host=172.17.0.1'
    volumes:
      - './application:/srv/badger:rw'
    working_dir: '/srv/badger'
    command: 'php-fpm -F'
    networks:
      - 'badger'

  httpd-back:
    image: 'httpd:2.4'
    environment:
      APP_ENV: '${APP_ENV:-prod}'
    depends_on:
      - 'fpm'
    ports:
      - '${DOCKER_PORT_HTTP:-8001}:80'
    volumes:
      - './application:/srv/badger:ro'
      - './infrastructure/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro'
      - './infrastructure/httpd/back.conf:/usr/local/apache2/conf/vhost.conf:ro'
    networks:
      - 'badger'

  db:
    image: 'postgres:12.1'
    ports:
      - '${DOCKER_PORT_POSTGRES:-5434}:5432'
    networks:
      - 'badger'

networks:
  badger:

