version: '2'

services:
  fpm:
    image: 'akeneo/fpm:php-7.2'
    user: 'docker'
    volumes:
      - './:/srv/badger'
    working_dir: '/srv/badger'
    networks:
      - 'badger'

  node:
    image: 'juliensnz/node'
    user: 'node'
    volumes:
      - './:/srv/badger'
    working_dir: '/srv/badger'
    networks:
      - 'badger'

  httpd:
    image: 'httpd:2.4'
    depends_on:
      - 'fpm'
    ports:
      - '${DOCKER_PORT_HTTP}:80'
    volumes:
      - './:/srv/badger:ro'
      - './docker/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro'
      - './docker/badger.conf:/usr/local/apache2/conf/vhost.conf:ro'
    networks:
      - 'badger'

networks:
  badger:
