services:
     ### handler
    Badger\Gamification\Application\SignUpHandler:
        public: true
        arguments:
            $memberRepository: '@Badger\Gamification\Domain\Repository\MemberRepository'
        tags:
            - { name: command_handler, handles: 'Badger\Gamification\Application\SignUp' }

    Badger\Gamification\Application\ClaimABadgeHandler:
        public: true
        arguments:
            $badgeRepository: '@Badger\Gamification\Domain\Repository\BadgeRepository'
            $memberRepository: '@Badger\Gamification\Domain\Repository\MemberRepository'
        tags:
            - { name: command_handler, handles: 'Badger\Gamification\Application\ClaimABadge' }
