services:
     ### handler
    Badger\Gamification\Application\SignUpHandler:
        public: true
        tags:
            - { name: command_handler, handles: 'Badger\Gamification\Application\SignUp' }
