doctrine:
    dbal:
        url: 'pgsql://postgres:postgres@db:5432/postgres'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'

        types:
          badge_id: Badger\Gamification\Infrastructure\Storage\Doctrine\Mapping\Badge\BadgeIdType
          badge_title: Badger\Gamification\Infrastructure\Storage\Doctrine\Mapping\Badge\BadgeTitleType
          badge_description: Badger\Gamification\Infrastructure\Storage\Doctrine\Mapping\Badge\BadgeDescriptionType
          member_id: Badger\Gamification\Infrastructure\Storage\Doctrine\Mapping\Member\MemberIdType
          member_name: Badger\Gamification\Infrastructure\Storage\Doctrine\Mapping\Member\MemberNameType

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
          Badge:
            is_bundle: false
            type: yml
            dir: '%kernel.project_dir%/src/Gamification/Infrastructure/Storage/Doctrine/Mapping/Badge'
            prefix: 'Badger\Gamification\Domain\Badge'
            alias: Gamification
          Member:
            is_bundle: false
            type: yml
            dir: '%kernel.project_dir%/src/Gamification/Infrastructure/Storage/Doctrine/Mapping/Member'
            prefix: 'Badger\Gamification\Domain\Member'
            alias: Gamification
